fix(#67): 코드 자동검사 수정 - 코드 규칙 위반하면 커밋 막도록 설정

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,38 +5,30 @@ FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.kts?$' || t
 [ -z "$FILES" ] && exit 0
 
 # 2) ktlint 자동 포매팅
+echo $FILES
+set +e
 echo "🔧 ktlint formatting..."
 ./ktlint -F $FILES
+if [ $? -ne 0 ]; then
+  echo "✖️ ktlint violations detected. Ktlint Check Failed..."
+  set -e
+  exit 1
+else [ $? -eq 0 ];
+  echo "✅ ktlint Check passed"
+fi
 
 # 3) 다시 스테이지
 git add $FILES
 
-# 4) ktlint 검증 (auto-fix 불가 위반이 있는지 확인)
-#echo "🚨 ktlint checking..."
-./ktlint $FILES
-if [ $? -ne 0 ]; then
-  echo "✖️ ktlint violations detected. Ktlint Check Failed..."
-fi
-
-if [ $? -eq 0 ]; then
-  echo "✅ ktlint checking passed"
-fi
-
 # 5) detekt 자동 수정
 echo "🔧 detekt auto-correct..."
-./gradlew detektStaged -PstagedFiles="$FILES"
-
-git add $FILES
-
-# 6) detekt strict 검사
-#echo "🚨 detekt checking..."
-./gradlew detektStaged -PstagedFiles="$FILES"
-
+./gradlew detektStaged -PstagedFiles="$FILES" --quiet
 if [ $? -ne 0 ]; then
   echo "✖️ Detekt violations detected. Detekt Check Failed..."
-fi
-
-if [ $? -eq 0 ]; then
+  set -e
+  exit 1
+else
+  git add $FILES
   echo "✅ Detekt checks passed."
   exit 0
 fi
